theme: jekyll-theme-slate
title: colorfi
description: Empowering Companies Into Web 3.0 
author: 295 Madison Avenue 12th Floor, New York, NY 10017
extra_footer: 295 Madison Avenue 12th Floor, New York, NY 10017
footer: 295 Madison Avenue 12th Floor, New York, NY 10017
