theme: jekyll-theme-slate
title: colorAI 
description: Innovative Fintech strategies for the 21st Century
author: 295 Madison Avenue 12th Floor, New York, NY 10017
extra_footer: 295 Madison Avenue 12th Floor, New York, NY 10017
footer: 295 Madison Avenue 12th Floor, New York, NY 10017
