theme: jekyll-theme-slate
title: colorAI 
description: driving companies into web3
author: 295 Madison Avenue 12th Floor, New York, NY 10017
extra_footer: 295 Madison Avenue 12th Floor, New York, NY 10017
footer: 295 Madison Avenue 12th Floor, New York, NY 10017
